  const ViewAttributes = [
    "view_id",
    "source_id",
    "data_type",
    "interval_version",
    "geography_version",
    "version",
    "source_url",
    "publisher",
    "table_schema",
    "table_name",
    "data_table",
    "download_url",
    "tiles_url",
    "start_date",
    "end_date",
    "last_updated",
    "statistics",
    "metadata",
    "user_id",
    "etl_context_id",
    "view_dependencies",
    "active_start_timestamp",
    "active_end_timestamp",
    "_created_timestamp",
    "_modified_timestamp",
  ];

module.exports = ViewAttributes;
